### ISSUE TITLE
Performance testing of Bulk / Async product save

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#1]
We have to measure performance of Bulk API import based on 1000 products from import start till all products will appear in Magento backend.
This performance also can me measured with multiple consumers running at the same time.

Also we have to make performance testing of default Magento import with 1000 products in csv file.

### Bulk API
Measurement 1: 
Products: 1000
Consumers: starting from 1 till first time then product import will be failed

Measurement 2: 
Products: 10000
Consumers: starting from 1 till first time then product import will be failed

### Default Import/Export
Measurement 1: 
Products: 1000

Measurement 2: 
Products: 10000

### Results
How much time parred from import start till all products will appear in Magento backend.

Result have to be compared and based on this information decision will be made if we have to implement import/export

One more decision have to me made here: how many consumers we can use at same time without any problem on Magento side. This info will be nice to provide with documentation

## PR
PR can me made with testing results and also with testing scripts

Original issue: https://github.com/magento-engcom/bulk-api/issues/33

**Comment by vrann** [comment]
Scenarios to test:
- individual product save through the bulk API. Coming from PIM 1-10 product; Here the most interesting is update;
- during update all product data is updated
- writing the set of products 100 products; 100K products; Here we would rather test create product scenario

Environment:
- repeatable env to measure improvement

**Comment by naydav** [comment]
Closed because this repository is related only to **Asynchronous Import Functionality**

@nuzil , if the task is still actual, please create an issue in
https://github.com/magento/community-features for **a feature request**
or in https://github.com/magento/magento2/issues for **a bug**
Thanks
