### ISSUE TITLE
Add Operation Status validator

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#100]
### Summary (*)
Currently in Magento\Framework\Bulk\OperationInterface we have a set of statuses in Constants and then in setStatus implementation we do not validate if status we receiving is generally existed. 

### Proposed solution
* Create statuses Pool
* Define list of statuses by using di.xml arguments for a class
* Implement validator of existed values
* on setStatus validate if status we are trying to set existed
* If status is not existed - throw and exception back

**Comment by sedonik** [comment]
Hi @nuzil,

I have added changes according to description and created   [Pull Request](https://github.com/magento/async-import/pull/108).

Please check.
Thanks.

**Comment by sedonik** [comment]
Hi @nuzil,

I have created new [PR](https://github.com/magento/async-import/pull/110) for adding changes to 2.3-develop branch because changes are related to module "AsynchronousOperations" of the main branch(2.3-develop). 

Please check.
Thanks.

**Comment by naydav** [comment]
Closed because this repository is related only to **Asynchronous Import Functionality**

@nuzil , if the task is still actual, please create an issue in
https://github.com/magento/community-features for **a feature request**
or in https://github.com/magento/magento2/issues for **a bug**
Thanks
