### ISSUE TITLE
Implement support of Store Scopes for DB MessageQueues

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#103]
Currently Message Queue can be used by using Database as queue system.

Problem of such implementation, that messages are not storing any information about store for which this request will be executed.

So if for example you will create a custom message for NOT default store, consumer will still automatically read and will execute it in default scope.

We need to implement support of stores, so messages are always executed in the same scope as they are create

Example of  implementation for AMQP
https://github.com/magento/async-import/pull/102

**Comment by naydav** [comment]
Closed because this repository is related only Asynchronous Import Functionality

@nuzil, if the task is still actual, please create an issue in
https://github.com/magento/community-features for a feature request
or in https://github.com/magento/magento2/issues for a bug
Thanks
