### ISSUE TITLE
Fix file type in URL to "csv"

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#106]
### Summary (*)
In this implementation
https://github.com/magento/async-import/blob/asynchronous-import-module/app/code/Magento/ImportService/etc/webapi.xml#L10

We have source type as param here, but its have to be "csv" type fixed.
Also we have to change naming for interfaces cause they are CSV related

So to SourceCsvUploadInterface and so on

**Comment by sedonik** [comment]
Hi @nuzil,

I have added changes to the code. And created [PR](https://github.com/magento/async-import/pull/109) .
Please check is it correct.

Thank you.
