### ISSUE TITLE
Performance Testing of Async API

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#12]
API Scenarios to test:

- individual product save through the bulk API. Coming from PIM 1-10 product; Here the most interesting is update;
- during update all product data is updated
- writing the set of products 100 products; 100K products; Here we would rather test create product scenario

## Accept Requests Tests
Async / Bulk - accept request: 
Baseline Measurement:

### Case 1 (calculate Response time): 
* Red: Synchronous Requests -> starting from 1 simultaneous request and rising to 1000 requests.
* Blue: Asynchronous Requests -> starting from 1 simultaneous request and rising to 1000 requests.
* Green: Bulk Requests -> starting from 10 in each Bulk request and till 1000 in each bulk request. Step: 10 

### Case 2 (calculate amount of errors - 5xx): 
* Red: Synchronous Requests -> starting from 1 simultaneous request and rising to 1000 requests.
* Blue: Asynchronous Requests -> starting from 1 simultaneous request and rising to 1000 requests.
* Green: Bulk Requests -> starting from 10 in each Bulk request and till 1000 in each bulk request. Step: 10 

As Result: 
2 diagrams.
1) Response time diagram
2) Errors diagram

Tables:

Response time:  
Lines: Red, Blue. Green
Columns: from 1 - 1000
Cells: in each cell average response time for a column

Errors amount: 
Lines: Red, Blue. Green
Columns: from 1 - 1000
Cells: in each cell amount of failed requests

## Products creation execution tests
Measurement have to calculate time of full circle till product is physically created in Magento Backend

### 1 consumer: 

* Red: Synchronous Requests -> starting from 1 simultaneous request and rising to 1000 requests.
* Blue: Asynchronous Requests -> starting from 1 simultaneous request and rising to 1000 requests.
* Green: Bulk Requests -> starting from 10 in each Bulk request and till 1000 in each bulk request. Step: 10 

From JMETER: 
Table with report: 
SKU | Request Send timestamp (incl. Milliseconds)

From Magento: 
Table with report
SKU | Product creation completed timestamp (incl. Milliseconds)

Result: 
We will merge 2 tables together. And we can generate report diagram. 

Workflow: 
- jMeter starts import and create file with amount of products it want to create
- Magento after each product is saved count amount of saved products and then its equal with jMeter report, custom script will be started which will merge 2 report tables together and will start jMeter command which will generate report diagram

### 2-100 consumers 
Repeat test before with multiple consumers running

# What we want to test:
- how long does it take for client to send products information to the async api
- how long will it take for consumer to persist the data from the message queue to the database
- how many consumers we can run in parallel when persisting products

# What have to be delivered: 
- jMeter scripts
- Documentation
- Script for measuring response time on Magento side
- Result diagrams 

### FYI: 

Environment:
- repeatable env to measure improvement
- framework for the tests to write the scenarios

Checking that consumers finished processing:
- check that operation successfully completed. Poll the status from the Async status API

Topology:
- tests running on separate instance
- Consumer is running on separate instance
- Magento on separate instance

Product Set:
- get generator from the Performance team

Server configuration:
guarantee at least 1 web node (define the requirements to the web server)
guarantee at least 1 mysql node (define the requirements to the mysql server)
guarantee at least 1 consumers node (define the requirements to the consumer server)
running Indexation for the consumer: measure both: on save and on schedule.

Dockerfile can be used for configuration of the nodes
Docker compose file can be used for description

PHP POST limit: %define the proposed limit on the size POST%

Possible Tools to use for load generation: Gatling, Tsung, JMeter
Deliverable: PR to the main repository with the testing tools, scripts, Docerfile

# Memory consumption of the consumers
- measure the memory consumption of the consumers
Document: best practice on consuming messages from the queue. PR in documentatiuon

**Comment by naydav** [comment]
Closed because this repository is related only Asynchronous Import Functionality

@nuzil, if the task is still actual, please create an issue in
https://github.com/magento/community-features for a feature request
or in https://github.com/magento/magento2/issues for a bug
Thanks
