### ISSUE TITLE
Create new configuration file for Storages

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#125]
### Summary (*)
As we are talking about services isolations, we need to create configuration, where particular objects import will be sent to via api, so we need to create new config file:

import_service_storage.xml

Example:
```
<?xml version="1.0"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<storages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_ImportService:etc/import_service.xsd">

        <storage name="magento_rest" class="Magento\ImportService\Model\Storage\MagentoRest" />

</storages> 
```

Here will be defined storage and also class that will manage data send

Please create config file, schema and config reader

**Comment by Stepa4man** [comment]
@edenduong 
Hey man, are you ready for real contribution?
Tired from fixing bugs? Want to create new Magento functionality and be a pioneer of cool stuff? Try to participate here.

**Comment by Stepa4man** [comment]
@edenduong so what? Are you with us?

**Comment by edenduong** [comment]
> @edenduong so what? Are you with us?

I am reading about the purpose of this module. Do you have the requirement or any docs of this module?

**Comment by nuzil** [comment]
Hi @edenduong 
We are refactoring base module now, I will keep you in loop.
On this Wednesday we will have backlog ready and base implementation, so you will get all information
