### ISSUE TITLE
Align csv_separator and csv_delimiter attributes

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#128]
### Preconditions (*)
Currently when you are uploading new source, you can have following body or upload/update request

```
{
  "source": {
      "import_data": "U0tVLFRpdGxlCiJTS1UgMSIsIlRpdGxlIDEi",
      "import_type": "base64_encoded_data",
      "format": {
        "delimiter": ",",
        "enclosure": "\"",
        "enclosure": ",",
        "multiple_value_separator": "|"
      }
  }
}
```

csv_separator and csv_delimiter are have the same purpose, so please remove "csv_separator" from the body and align code so, that everywhere is "csv_delimiter" used

**Comment by naydav** [comment]
https://github.com/magento/async-import/pull/187
