### ISSUE TITLE
Define User-friendly topic names

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#13]
Currently all Topic - names for Async API are generated based on WebApi. 
But on a backend of Magento user will see a messages that contain topic names. 

As nice approach will be nice to make possible to define User-friendly names to be displayed on a Backend of Magento

We decided to extend webapi.xml with "description" attribute and then generate communication.xml also with "description" attribute and then it can be used on those messages.

## ToDO:
- extend webapi.xml with "description" param
- extend communication.xml with "description" param
- extend generation of communication.xml for Async API with description param taken from webapi.xml
- User description param value for fill magento_bulk table "description" column

**Comment by nuzil** [comment]
Hi @phoenix128, maybe you have some progress on this task already?

**Comment by sedonik** [comment]
Hi @nuzil,

I am investigating this ticket and faced with a question about workflow.

Not very clear what does it meant phrase: "extend generation of communication.xml for Async API with description param taken from web api.xml"

Could you advise, please?

**Comment by nuzil** [comment]
Hi @sedonik, 

Currently Magento Asynchronous API "generating" communication.xml for all API requests based on webapi.xml.

As we will add "description" field to webapi.xml, we need, on a step when this "generation" happening, to use this description from webapi.xml.

Its happening here:
app/code/Magento/WebapiAsync/Code/Generator/Config/RemoteServiceReader/Communication.php

**Comment by naydav** [comment]
Closed because this repository is related only **Asynchronous Import Functionality**

@nuzil, if the task is still actual, please create an issue in 
https://github.com/magento/community-features for **a feature request**
or in https://github.com/magento/magento2/issues for **a bug**
Thanks
