### ISSUE TITLE
Make UUID for source uploading not required

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#146]
### Story
#138 [Story] Sources Management

### Description (*)
For source upload, currently UUID is required field. 
We cannot expect that each customer or integrator will have own UUIDs.
Please make it not required.

If UUID is not transferred, then it have to be generated by Magento end returned back as a string from `Magento\AsynchronousImportApi\Api\SaveSourceInterface`

**Comment by naydav** [comment]
Closed as not relevant
