### ISSUE TITLE
Make UUID for import starting not required

### ISSUE THREAD

**Issue by naydav** [magento/async-import#153]
### Story
#150 [Story] Import Process

### Description (*)
For import starting, currently, UUID is a required field. 
See
`\Magento\AsynchronousImportApi\Api\StartImportInterface`
`\Magento\AsynchronousImportApi\Api\Data\ImportInterface`

Should be an optional field, if not passed should be generated on Magento side

If UUID is not transferred, then it have to be generated by Magento end returned back as a string from `\Magento\AsynchronousImportApi\Api\StartImportInterface`

**Comment by naydav** [comment]
Hi @M-Andriy,
Do you have any progress with this ticket?
Thanks

**Comment by nuzil** [comment]
After latest changes UUID is not anymore required field. Issue can be closed
