### ISSUE TITLE
Create "StringReplaceConvertor" converting rule

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#157]
### Story
#154 [Story] Converting Rules

### Pre-conditions
See story

### Description
For converting rules, we have to create "StringReplaceConvertor" rule.

Name: **StringReplaceConvertor**
Example:
```
....
    "convertingRules": [
        {
            "name": "StringReplaceConvertor",
            "sort": 10,
            "paramethers": {
                "apply_to": ["website"],
                "search": "string",
                "replace": "string"
            }
        }
    ]
```

Module to implement in: **Magento_AsynchronousImport**

Basic: https://www.php.net/manual/ru/function.str-replace.php

**Action**: it will take "apply_to" columns and will apply str_repace with appropriate params to this column value.

If at least one column in apply_to is not existed, throw an exception

**Comment by naydav** [comment]
https://github.com/magento/async-import/pull/198
