### ISSUE TITLE
Create "StringToLower" converting rule

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#160]
### Story
#154 [Story] Converting Rules

### Pre-conditions
See story

### Description
For converting rules, we have to create "StringToLower" rule.

Name: ** StringToLower**
Example:
```
....
    "convertingRules": [
        {
            "name": "StringToLower",
            "sort": 10,
            "paramethers": {
                "apply_to": ["attribute_a"]
            }
        }
    ]
```

Module to implement in: **Magento_AsynchronousImport**

Action: it will take "apply_to" columns and put all values there to lower case

If at least one column in apply_to is not existed, throw an exception

**Comment by naydav** [comment]
Hello @ffalkone,
Picked up this ticket due to inactivity.
Ping me or @nuzil if you need some recommendation with a new issue.
Thanks

**Comment by naydav** [comment]
https://github.com/magento/async-import/pull/226
