### ISSUE TITLE
Create "UcFirst" converting rule

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#161]
### Story
#154 [Story] Converting Rules

### Pre-conditions
See story

### Description
For converting rules, we have to create "UcFirst" rule.

Name: ** UcFirst**
Example:
```
....
    "convertingRules": [
        {
            "name": "UcFirst",
            "sort": 10,
            "paramethers": {
                "apply_to": ["website"]
            }
        }
    ]
```

Module to implement in: **Magento_AsynchronousImport**

Action: it will take "apply_to" columns and will make first letter as upper case

If at least one column in apply_to is not existed, throw an exception

**Comment by naydav** [comment]
https://github.com/magento/async-import/pull/205
