### ISSUE TITLE
Create "StringToUpper" converting rule

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#162]
### Story
#154 [Story] Converting Rules

### Pre-conditions
See story

### Description
For converting rules, we have to create "StringToUpper" rule.

Name: ** StringToUpper**
Example:
```
....
    "convertingRules": [
        {
            "name": "StringToUpper",
            "sort": 10,
            "apply_to": ["attribute_b"],
            "parameters": {
                
            }
        }
    ]
```

Module to implement in: **Magento_AsynchronousImport**

Action: it will take "apply_to" columns and will make value as uppercase

If at least one column in apply_to is not existed, throw an exception

**Comment by naydav** [comment]
https://github.com/magento/async-import/pull/195
