### ISSUE TITLE
Create "RemoveField" converting rule

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#183]
### Story
#154 [Story] Converting Rules

### Pre-conditions
See story

### Description
For converting rules, we have to create "RemoveField" rule.

Name: **RemoveField**
Example:
```
....
    "convertingRules": [
        {
            "name": "RemoveField",
            "sort": 10,
            "paramethers": {
                "apply_to": ["website", "column2"]
            }
        }
    ]
```

Module to implement in: **Magento_AsynchronousImport**

Action: it will take "apply_to" columns and will drop all columns from income object with those names

No Exception

**Comment by naydav** [comment]
https://github.com/magento/async-import/pull/203
