### ISSUE TITLE
Implement Swagger for BULK API

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#25]
### Summary (*)
Currently we have Swagger implemented for Async API, will be also nice to have BULK API Swagger implementation

Follow up from https://github.com/magento-engcom/bulk-api/issues/28

**Comment by naydav** [comment]
Closed because this repository is related only *Asynchronous Import Functionality*

@nuzil, if the task is still actual, please create an issue in 
https://github.com/magento/community-features for *a feature request*
or in https://github.com/magento/magento2/issues for *a bug*
Thanks
