### ISSUE TITLE
Status reporting for the entities

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#26]
Goal:  There should be a way to retrieve the responses of the operation invoked asynchronously.

### 1. Tracking of the statuses of individual entities as as a separate endpoints for the every individual entity which is persisted as a part of the bulk.

I.e let’s take `POST /rest/V1/products` as an example. 
* Asynchronous request corresponding to it is `POST /rest/async/V1/products`. 
* response is
```
202 Accepted 

{bulk_id: xxxxx}
```
What should be implemented as a part of this story is an endpoint
`GET /rest/status/V1/products/:uuid` which will return

```
[
   {response from product 1 save}
   {response from product 2 save}
   {response from product 3 save}
]
```

we can have a second status endpoint which includes the operationId, this can return the synchronous schema's response body from the status endpoint.

Then I can implement something like this in Swagger to describe it:
```
paths:
  /status/productOperationName/:uuid:
    get:
      summary: Returns productOperationName response
    responses:
        '200':
          description: A JSON object the productOperationName response
          content:
            application/json:
              schema:
                  - $ref: '#catalogDataProductInterface'
 /status/customerOperationName/:uuid:
    get:
    summary: Returns customerOperationName response
    responses:
    '200':
        description: A JSON object the customerOperationName response
        content:
        application/json:
            schema:
                - $ref: '#customerCustomerDataInterface'
```
 we can have the uuid before the operation name

**Comment by nuzil** [comment]
https://github.com/magento-engcom/bulk-api/issues/12

**Comment by naydav** [comment]
Closed because this repository is related only **Asynchronous Import Functionality**

@nuzil, if the task is still actual, please create an issue in 
https://github.com/magento/community-features for **a feature request**
or in https://github.com/magento/magento2/issues for **a bug**
Thanks
