### ISSUE TITLE
Incremental Updates

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#27]
Support for incremental updates should address the problem of the third-party systems which persists multiple entities without checking did they really change. Every entity which is persisted should have hash generated for the data. When persistence operation starts, it will load the entity from the database and calculate the hash on key data which is imported. In case if the hash is not changed, an entity should be skipped from the persistence.

Redis can be used in middleware to check is there differences between post requests; Incremental updates.
Besides, Resource Models can be optimized to be able to calculate the hash before persistence starts

**Comment by nuzil** [comment]
Solution have to be discussed before implementation

**Comment by naydav** [comment]
Closed because this repository is related only **Asynchronous Import Functionality**

@nuzil, if the task is still actual, please create an issue in 
https://github.com/magento/community-features for **a feature request**
or in https://github.com/magento/magento2/issues for **a bug**
Thanks
