### ISSUE TITLE
Redis Bulk API / Async Api implementation

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#3]
## Idea

Initial idea is to avoid of Database usage during execution of BULK API / Async api calls. 

Currently Database is using for Operations and Operation statuses storage. Also it using for receive objects information and attributes on a step of call validation.

We have to implement this part in way, that it is possible to store Operations and their statuses in Redis database. 
Objects attributes have to be cached by Magento, and in case of enabled cache database also will not be loaded

**Comment by vkublytskyi** [comment]
Added branch `redis` to implement this epic and deliver working solution to the Magento mainline
