### ISSUE TITLE
Create Api-Functional tests coverage for Base64 Processor

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#68]
### Summary (*)
We need to core with API functional tests functionality of Base64 Processor.

### Examples (*)
Original PR: 
https://github.com/magento/async-import/pull/45

Also some example can be found here:
https://github.com/magento/async-import/pull/40/files#diff-9b9e92ee3b63224a2d1b20a84f5ee968

**Comment by naydav** [comment]
Closed due to https://github.com/magento/async-import/issues/140
