### ISSUE TITLE
Create Redis Framework implementation

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#7]
lib/Magento/Framework/Redis -- implements storage-specific interfaces using the connection to the Redis via Credis composer library

have to implement https://app.zenhub.com/workspace/o/magento/async-import/issues/6 interface

**Comment by MTheProgrammer** [comment]
#mm18pl

**Comment by vkublytskyi** [comment]
@MTheProgrammer, please implement Redis integration based on currently available `Magento\Framework\KeyValue` interfaces from `create_keyvalue_framework_module` branch (see PR #11) as it is better to not merge framework interfaces before we prove they are usable.

**Comment by nuzil** [comment]
@MTheProgrammer do you have any update for this issue?
