### ISSUE TITLE
Create Redis module

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#8]
app/code/Magento/Redis -- module responsible for reading environment configuration and injecting it to the Redis library

have to implement https://app.zenhub.com/workspace/o/magento/async-import/issues/7

**Comment by ualinker** [comment]
@nuzil 
I assume this one has been done within https://github.com/magento/async-import/pull/16 ?

**Comment by nuzil** [comment]
You covered it with PR #22 
As idea changed after we decided to call redis directly from AsyncOperation
