### ISSUE TITLE
Store Bulk operations in Redis storage

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#82]
Asynchronous API is writing operation statuses, request body, topic name and UUID info "magento_operation" table and "magento_bulk"
We have to implement possibility to write and read Magento Operations into Redis Database and not into Magento DB.

Currently Bulk operation executed scheduleBulk in app/code/Magento/AsynchronousOperations/Model/BulkManagement.php

```
try {
            /** @var \Magento\AsynchronousOperations\Api\Data\BulkSummaryInterface $bulkSummary */
            $bulkSummary = $this->bulkSummaryFactory->create();
            $this->entityManager->load($bulkSummary, $bulkUuid);
            $bulkSummary->setBulkId($bulkUuid);
            $bulkSummary->setDescription($description);
            $bulkSummary->setUserId($userId);
            $bulkSummary->setUserType($userType);
            $bulkSummary->setOperationCount((int)$bulkSummary->getOperationCount() + count($operations));

            $this->entityManager->save($bulkSummary);

            $connection->commit();
        } catch (\Exception $exception) {
            $connection->rollBack();
            $this->logger->critical($exception->getMessage());
            return false;
        }
```

app/code/Magento/AsynchronousOperations/Model/ResourceModel/Operation

```
public function createByTopic($topicName, $entityParams, $groupId)
    {
        $this->messageValidator->validate($topicName, $entityParams);
        $encodedMessage = $this->messageEncoder->encode($topicName, $entityParams);

        $serializedData = [
            'entity_id'        => null,
            'entity_link'      => '',
            'meta_information' => $encodedMessage,
        ];
        $data = [
            'data' => [
                OperationInterface::BULK_ID         => $groupId,
                OperationInterface::TOPIC_NAME      => $topicName,
                OperationInterface::SERIALIZED_DATA => $this->jsonSerializer->serialize($serializedData),
                OperationInterface::STATUS          => OperationInterface::STATUS_TYPE_OPEN,
            ],
        ];

        /** @var \Magento\AsynchronousOperations\Api\Data\OperationInterface $operation */
        $operation = $this->operationFactory->create($data);
        return $this->entityManager->save($operation);
    }
```

This operation takes a lot of process time when we are executing bulk requests. 
 
### Summary (*)
We have to use Redis storage for storing bulk operation statuses in Redis storage.

### ToDos
- Add new config section in env.php file to be able define own connection for Redis storage
- Implement of saving Operations inside of the Redis in case if connection in env.php exists
- We can exclude of usage of magento_bulk table in case of Redis usage

**Comment by nuzil** [comment]
We have already related PR to this issue:
https://github.com/magento/async-import/pull/22

Developer who will take it can process with this PR, or he can create his own based on this one.

**Comment by naydav** [comment]
Closed because this repository is related only to **Asynchronous Import Functionality**

@nuzil , if the task is still actual, please create an issue in
https://github.com/magento/community-features for **a feature request**
or in https://github.com/magento/magento2/issues for **a bug**
Thanks
