### ISSUE TITLE
Bulk Operations performance improvements

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#83]
Asynchronous API is writing operation statuses, request body, topic name and UUID info "magento_operation" table and "magento_bulk"
Those operations are atomic and executing always one after another.

Currently Bulk operation executed scheduleBulk in app/code/Magento/AsynchronousOperations/Model/BulkManagement.php

```
try {
            /** @var \Magento\AsynchronousOperations\Api\Data\BulkSummaryInterface $bulkSummary */
            $bulkSummary = $this->bulkSummaryFactory->create();
            $this->entityManager->load($bulkSummary, $bulkUuid);
            $bulkSummary->setBulkId($bulkUuid);
            $bulkSummary->setDescription($description);
            $bulkSummary->setUserId($userId);
            $bulkSummary->setUserType($userType);
            $bulkSummary->setOperationCount((int)$bulkSummary->getOperationCount() + count($operations));

            $this->entityManager->save($bulkSummary);

            $connection->commit();
        } catch (\Exception $exception) {
            $connection->rollBack();
            $this->logger->critical($exception->getMessage());
            return false;
        }
```

app/code/Magento/AsynchronousOperations/Model/ResourceModel/Operation

```
public function createByTopic($topicName, $entityParams, $groupId)
    {
        $this->messageValidator->validate($topicName, $entityParams);
        $encodedMessage = $this->messageEncoder->encode($topicName, $entityParams);

        $serializedData = [
            'entity_id'        => null,
            'entity_link'      => '',
            'meta_information' => $encodedMessage,
        ];
        $data = [
            'data' => [
                OperationInterface::BULK_ID         => $groupId,
                OperationInterface::TOPIC_NAME      => $topicName,
                OperationInterface::SERIALIZED_DATA => $this->jsonSerializer->serialize($serializedData),
                OperationInterface::STATUS          => OperationInterface::STATUS_TYPE_OPEN,
            ],
        ];

        /** @var \Magento\AsynchronousOperations\Api\Data\OperationInterface $operation */
        $operation = $this->operationFactory->create($data);
        return $this->entityManager->save($operation);
    }
```

### Summary (*)
We need to change implementation in the way, that saving to database operation will be executed also in a Bulk, for save resources and execute saving to persistent store with one operation.

- Eliminate ->save() inside of foreach, but implement only one ->save() for multiple operations

### ToDos
- Change implementation in a way, that system save entities to persistent storage in bulk and not in single items

**Comment by naydav** [comment]
Closed because this repository is related only Asynchronous Import Functionality

@nuzil, if the task is still actual, please create an issue in
https://github.com/magento/community-features for a feature request
or in https://github.com/magento/magento2/issues for a bug
Thanks

**Comment by elvinristi** [comment]
naydav comment shows well that there will be no performance related improvements by Magento as they don't have any idea what it is :D 

and companies continue to patch their crap and keep long list of patches to keep Magento project runnable.
