### ISSUE TITLE
Cache EAV attributes of objects

### ISSUE THREAD

**Issue by nuzil** [magento/async-import#9]
This topic have to be discussed with next points: 
* New cache type? 
* Add new cache type in Backend
* Cache update on objects create / save

Currently when Async call executes, system reads a lot of EAV data from the system:

![Screen Shot 2018-07-31 at 15.15.00.png](https://images.zenhubusercontent.com/5a5670c84b5806bc2bc2414b/99a07d70-4329-46cb-8bb6-5463c7cfde6d)![Screen Shot 2018-07-31 at 15.14.54.png](https://images.zenhubusercontent.com/5a5670c84b5806bc2bc2414b/d046c94c-c2be-4870-8c5e-cef8b23d61be)

We have to cache required information in Magento cache for those data can be received without database usage.

So have to be provided new cache type: "EAV Objects structure"

Tests: 
with using of eav* tables - Total DB queries takes: 0,028ms
without eav* tables - Total DB queries takes: 0,008ms

**Comment by naydav** [comment]
Closed because this repository is related only Asynchronous Import Functionality

@nuzil, if the task is still actual, please create an issue in
https://github.com/magento/community-features for a feature request
or in https://github.com/magento/magento2/issues for a bug
Thanks
